import { useEffect, useState, type FormEvent } from "react"
import { useNavigate } from "react-router-dom"
import { Button, Input } from "@/components/ui"
import { completeOnboarding, getDepartments, type AddressFormData } from "@/services"

const emptyAddress: AddressFormData = { county: "", locality: "", street: "", number: "", apartmentBlock: "", floor: "", postalCode: "" }

export default function OnboardingPage() {
  const navigate = useNavigate(); const [departments, setDepartments] = useState<Array<{id:number;name:string}>>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState("")
  const [form, setForm] = useState({ departmentName: "", phoneNumber: "", role: "", employmentDate: new Date().toISOString().slice(0,10), address: emptyAddress })
  useEffect(() => { getDepartments().then(setDepartments).catch(() => setError("Nu s-au putut încărca departamentele.")) }, [])
  const setAddress = (key: keyof AddressFormData, value: string) => setForm((current) => ({ ...current, address: { ...current.address, [key]: value } }))
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await completeOnboarding(form); navigate("/") } catch (err) { setError(err instanceof Error ? err.message : "Datele nu au putut fi salvate.") } finally { setSaving(false) } }
  return <main className="mx-auto max-w-3xl p-6"><h1 className="text-2xl font-bold">Completează-ți profilul</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">Aceste date sunt necesare pentru rezervări și recomandări.</p><form onSubmit={submit} className="mt-6 space-y-5 rounded-2xl bg-[var(--card)] p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Departament<select required value={form.departmentName} onChange={(e) => setForm({...form, departmentName:e.target.value})} className="mt-1 w-full rounded-md border bg-background p-2"><option value="">Alege departamentul</option>{departments.map((department) => <option key={department.id} value={department.name}>{department.name}</option>)}</select></label><label className="text-sm font-semibold">Telefon<Input required value={form.phoneNumber} onChange={(e) => setForm({...form, phoneNumber:e.target.value})} placeholder="0712345678" /></label><label className="text-sm font-semibold">Rol<Input required value={form.role} onChange={(e) => setForm({...form, role:e.target.value})} /></label><label className="text-sm font-semibold">Data angajării<Input required type="date" value={form.employmentDate} onChange={(e) => setForm({...form, employmentDate:e.target.value})} /></label></div><h2 className="pt-2 text-lg font-bold">Adresă</h2><div className="grid gap-4 sm:grid-cols-2">{([['county','Județ'],['locality','Localitate'],['street','Stradă'],['number','Număr'],['apartmentBlock','Bloc'],['floor','Etaj'],['postalCode','Cod poștal']] as Array<[keyof AddressFormData,string]>).map(([key,label]) => <label key={key} className="text-sm font-semibold">{label}<Input required={key !== 'apartmentBlock' && key !== 'floor'} value={form.address[key]} onChange={(e) => setAddress(key,e.target.value)} /></label>)}</div>{error && <p className="text-sm text-destructive">{error}</p>}<Button type="submit" isLoading={saving}>Salvează și continuă</Button></form></main>
}
