import { Star } from "lucide-react"
import type { Colleague } from "@/types"
import { getInitials } from "@/utils"

interface ColleaguesTableProps { colleagues: Colleague[]; onToggleFavorite: (id: number) => void; onViewProfile: (colleague: Colleague) => void }

export function ColleaguesTable({ colleagues, onToggleFavorite, onViewProfile }: ColleaguesTableProps) {
  return <div className="max-w-[920px] overflow-x-auto rounded-[20px] border border-[var(--border)] bg-[var(--card)] shadow-[0_1px_6px_rgba(0,0,0,0.04)]"><table className="w-full min-w-[680px] table-fixed border-collapse"><colgroup><col style={{ width: "35%" }} /><col style={{ width: "20%" }} /><col style={{ width: "25%" }} /><col style={{ width: "10%" }} /><col style={{ width: "10%" }} /></colgroup><thead><tr className="border-b border-[var(--border)]"><th className="py-3 pt-[17px] pr-3 pb-3 pl-[22px] text-left text-xs font-semibold text-[var(--muted-foreground)]">Coleg</th><th className="px-3 py-3 pt-[17px] text-left text-xs font-semibold text-[var(--muted-foreground)]">Status</th><th className="px-3 py-3 pt-[17px] text-left text-xs font-semibold text-[var(--muted-foreground)]">Locație</th><th className="px-3 py-3 pt-[17px] text-left text-xs font-semibold text-[var(--muted-foreground)]">Favorit</th><th className="py-3 pt-[17px] pr-[22px] pl-3"><span className="sr-only">Profil</span></th></tr></thead><tbody>{colleagues.map((colleague) => <ColleagueRow key={colleague.id} colleague={colleague} onToggleFavorite={onToggleFavorite} onViewProfile={onViewProfile} />)}{colleagues.length === 0 && <tr><td className="px-6 py-[42px] text-center text-[var(--muted-foreground)]" colSpan={5}>Nu am găsit colegi care să corespundă căutării.</td></tr>}</tbody></table></div>
}

function ColleagueRow({ colleague, onToggleFavorite, onViewProfile }: { colleague: Colleague; onToggleFavorite: (id: number) => void; onViewProfile: (colleague: Colleague) => void }) {
  return <tr className="border-b border-[var(--border)] last:border-0 transition hover:bg-[var(--background)]/60"><td className="py-3 pr-3 pl-[22px] align-middle text-[13px]"><div className="flex items-center gap-[13px]"><span className="grid size-[30px] shrink-0 place-items-center rounded-full border-2 border-[var(--primary)] bg-[var(--secondary)] text-[11px] font-bold text-[var(--secondary-foreground)]">{getInitials(colleague.name)}</span><div><div className="leading-[1.1] font-bold text-[var(--foreground)]">{colleague.name}</div><div className="mt-[3px] text-[11px] leading-[1.1] text-[var(--muted-foreground)]">{colleague.role}</div></div></div></td><td className="px-3 py-3 align-middle text-[13px]"><span className={`inline-flex min-w-[74px] justify-center rounded-full px-2.5 py-1 text-[11px] font-bold ${colleague.status === "La birou" ? "bg-[var(--secondary)] text-[var(--secondary-foreground)]" : "bg-[var(--destructive)]/20 text-[var(--destructive)]"}`}>{colleague.status}</span></td><td className="px-3 py-3 align-middle text-xs font-semibold text-[var(--foreground)]">{colleague.floor}</td><td className="px-3 py-3 align-middle"><button type="button" className={`p-1 leading-none transition ${colleague.isFavorite ? "text-[var(--warning)]" : "text-[var(--border)] hover:text-[var(--warning)]"}`} onClick={() => onToggleFavorite(colleague.id)} aria-label={`${colleague.isFavorite ? "Elimină" : "Adaugă"} ${colleague.name} la favorite`}><Star size={19} fill={colleague.isFavorite ? "currentColor" : "none"} /></button></td><td className="py-3 pr-[22px] pl-3 align-middle"><button type="button" onClick={() => onViewProfile(colleague)} className="whitespace-nowrap bg-transparent p-0 text-xs font-bold text-[var(--primary)] hover:text-[var(--sidebar-accent-hover)] hover:underline">Vezi profil</button></td></tr>
}
